### ISSUE TITLE
[3pt,3pt] Review Majordomo implementation, make messaging structures less 0mq specific

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/opencmw-cpp#192]

**Comment by RalphSteinhagen** [comment]
This is in part also a follow-up item and entails the merging of the Broker/Worker and Client MdpMessage implementations outlined in https://github.com/fair-acc/opencmw-cpp/issues/181.

Presently the MDP message parts 'service name' and 'topic' are a bit confusing, maybe a better option would be to change the frame names and make them a bit more explicite, i.e.:

* 'service name' -> 'requested topic' -- *the URI/resource (including query) that the user requested in the first place*
* 'topic' -> 'reply topic' -- *the URI/resource including the original and additional query parameter) that the worker sends back*

This would help/simplify the subscription matching by always notifying the requested topic. The old 'service name' corresponded to to the URI path anyway.

*N.B. as a side note: the initial choice of removing and/or keeping the initial '/' in the path/service name wasn't as good because it causes a lot of ambiguity in other parts of the code. We should stick to the URI RFC definition.*

**Comment by frankosterfeld** [comment]
As I understand it, the actual zmq dependencies in the client are already solved, where Client.hpp is the ZMQ client, and RestClient*.hpp is ZMQ-free. One could think about separating them more clearly, and maybe rename Client to ZmqClient/move it to a custom namespace? 

Is this ticket only about removing the ZMQ lingo and concepts from the API, like detailed in Ralph's comment above? I'll wait for Ivan on that part, as according to Alex, this might overlap with his work on #194.

**Comment by RalphSteinhagen** [comment]
> 'service name' -> 'requested topic' -- the URI/resource (including query) that the user requested in the first place

The " (including query)" is confusing and wrong... the service name should include only the URI path (tbc. with '/' prefix). Sorry for the confusion. The path-only matching is needed because ZeroMQ/MDP allows only for prefix-based matching.
